/**
 * Datos de demostracion FICTICIOS. Simbolos reales, cantidades y precios
 * inventados. Todo lleva isDemo: true y la UI lo etiqueta como "Datos demo".
 * Permiten usar la aplicacion completa sin claves de ningun proveedor.
 */
import type { Asset, BrokerAccount, Quote, Transaction } from '../lib/domain'

export const DEMO_PORTFOLIO_TARGET_EUR = '23049.26'
export const DEMO_TOTAL_PNL_EUR = '709.46'
export const DEMO_TOTAL_RETURN = '0.0311'

export const DEMO_ACCOUNTS: BrokerAccount[] = [
  {
    id: 'demo-acc-broker',
    brokerName: 'Broker Demo',
    accountLabel: 'Cartera indexada (demo)',
    defaultCurrency: 'EUR',
    country: 'ES',
  },
  {
    id: 'demo-acc-broker-2',
    brokerName: 'Broker Demo 2',
    accountLabel: 'Acciones EEUU (demo)',
    defaultCurrency: 'EUR',
    country: 'ES',
  },
  {
    id: 'demo-acc-exchange',
    brokerName: 'Exchange Demo',
    accountLabel: 'Cripto (demo)',
    defaultCurrency: 'EUR',
  },
  {
    id: 'demo-acc-cash',
    brokerName: 'Banco Demo',
    accountLabel: 'Liquidez (demo)',
    defaultCurrency: 'EUR',
    country: 'ES',
  },
]

export const DEMO_ASSETS: Asset[] = [
  {
    id: 'demo-btc',
    symbol: 'BTC',
    name: 'Bitcoin',
    assetType: 'crypto',
    quoteCurrency: 'USD',
    providerIds: { coingecko: 'bitcoin', twelvedata: 'BTC/USD' },
    sector: 'Criptoactivo',
    country: 'Global',
    isDemo: true,
  },
  {
    id: 'demo-msci-world-etf',
    symbol: 'IWDA',
    name: 'iShares Core MSCI World UCITS ETF (Acc)',
    assetType: 'etf',
    quoteCurrency: 'EUR',
    isin: 'IE00B4L5Y983',
    exchange: 'Euronext Amsterdam',
    country: 'Global',
    sector: 'Renta variable global',
    providerIds: { twelvedata: 'IWDA' },
    holdings: [
      { symbol: 'AAPL', name: 'Apple', weight: '0.046' },
      { symbol: 'MSFT', name: 'Microsoft', weight: '0.041' },
      { symbol: 'NVDA', name: 'NVIDIA', weight: '0.039' },
      { symbol: 'AMZN', name: 'Amazon', weight: '0.024' },
      { symbol: 'META', name: 'Meta Platforms', weight: '0.018' },
      { symbol: 'TSLA', name: 'Tesla', weight: '0.014' },
    ],
    isDemo: true,
  },
  {
    id: 'demo-spx-etf',
    symbol: 'SXR8',
    name: 'iShares Core S&P 500 UCITS ETF (Acc)',
    assetType: 'etf',
    quoteCurrency: 'EUR',
    isin: 'IE00B5BMR087',
    exchange: 'XETRA',
    country: 'US',
    sector: 'Renta variable EEUU',
    providerIds: { twelvedata: 'SXR8' },
    holdings: [
      { symbol: 'AAPL', name: 'Apple', weight: '0.072' },
      { symbol: 'MSFT', name: 'Microsoft', weight: '0.066' },
      { symbol: 'NVDA', name: 'NVIDIA', weight: '0.058' },
      { symbol: 'AMZN', name: 'Amazon', weight: '0.039' },
      { symbol: 'META', name: 'Meta Platforms', weight: '0.026' },
      { symbol: 'TSLA', name: 'Tesla', weight: '0.019' },
    ],
    isDemo: true,
  },
  {
    id: 'demo-aapl',
    symbol: 'AAPL',
    name: 'Apple',
    assetType: 'stock',
    quoteCurrency: 'USD',
    exchange: 'NASDAQ',
    country: 'US',
    sector: 'Tecnologia',
    providerIds: { twelvedata: 'AAPL' },
    isDemo: true,
  },
  {
    id: 'demo-tsla',
    symbol: 'TSLA',
    name: 'Tesla',
    assetType: 'stock',
    quoteCurrency: 'USD',
    exchange: 'NASDAQ',
    country: 'US',
    sector: 'Consumo discrecional',
    providerIds: { twelvedata: 'TSLA' },
    isDemo: true,
  },
  {
    id: 'demo-cash-eur',
    symbol: 'EUR',
    name: 'Efectivo EUR',
    assetType: 'cash',
    quoteCurrency: 'EUR',
    sector: 'Liquidez',
    country: 'ES',
    isDemo: true,
  },
]

export const DEMO_TRANSACTIONS: Transaction[] = [
  {
    id: 'demo-tx-btc-1',
    accountId: 'demo-acc-exchange',
    assetId: 'demo-btc',
    type: 'buy',
    datetime: '2025-08-12T09:30:00Z',
    investedAmount: '8000',
    investedCurrency: 'EUR',
    quantity: '0.1368745714',
    executionPrice: '58372.32',
    quoteCurrency: 'EUR',
    fee: null,
    feeCurrency: null,
    sourceType: 'historical_estimate',
    confidence: 'medium',
    estimationNotes: 'Precio de ejecucion ficticio derivado del historico demo.',
    isDemo: true,
  },
  {
    id: 'demo-tx-iwda-1',
    accountId: 'demo-acc-broker',
    assetId: 'demo-msci-world-etf',
    type: 'buy',
    datetime: '2025-09-04T14:00:00Z',
    investedAmount: '5600',
    investedCurrency: 'EUR',
    quantity: '58.5007106599',
    executionPrice: '95.73',
    quoteCurrency: 'EUR',
    fee: null,
    feeCurrency: null,
    sourceType: 'exact',
    confidence: 'exact',
    isDemo: true,
  },
  {
    id: 'demo-tx-spx-1',
    accountId: 'demo-acc-broker',
    assetId: 'demo-spx-etf',
    type: 'buy',
    datetime: '2025-10-10T14:00:00Z',
    investedAmount: '2300',
    investedCurrency: 'EUR',
    quantity: '4.1422019623',
    executionPrice: '555.26',
    quoteCurrency: 'EUR',
    fee: null,
    feeCurrency: null,
    sourceType: 'exact',
    confidence: 'exact',
    isDemo: true,
  },
  {
    id: 'demo-tx-spx-sale-1',
    accountId: 'demo-acc-broker',
    assetId: 'demo-spx-etf',
    type: 'sell',
    datetime: '2026-05-15T14:00:00Z',
    investedAmount: '472.20',
    investedCurrency: 'EUR',
    quantity: '0.82',
    executionPrice: '575.85',
    quoteCurrency: 'EUR',
    fee: null,
    feeCurrency: null,
    sourceType: 'exact',
    confidence: 'exact',
    isDemo: true,
  },
  {
    id: 'demo-tx-aapl-1',
    accountId: 'demo-acc-broker',
    assetId: 'demo-aapl',
    type: 'buy',
    datetime: '2025-11-20T11:00:00Z',
    investedAmount: '2020',
    investedCurrency: 'EUR',
    quantity: '10',
    executionPrice: '202',
    quoteCurrency: 'EUR',
    fee: null,
    feeCurrency: null,
    sourceType: 'historical_estimate',
    confidence: 'medium',
    estimationNotes: 'Precio de ejecucion ficticio derivado del historico demo.',
    isDemo: true,
  },
  {
    id: 'demo-tx-aapl-2',
    accountId: 'demo-acc-broker-2',
    assetId: 'demo-aapl',
    type: 'buy',
    datetime: '2026-02-18T14:00:00Z',
    investedAmount: '1700.89',
    investedCurrency: 'EUR',
    quantity: '8.4394',
    executionPrice: '201.54',
    quoteCurrency: 'EUR',
    fee: null,
    feeCurrency: null,
    sourceType: 'historical_estimate',
    confidence: 'medium',
    estimationNotes: 'Precio de ejecucion ficticio derivado del historico demo.',
    isDemo: true,
  },
  {
    id: 'demo-tx-tsla-1',
    accountId: 'demo-acc-broker-2',
    assetId: 'demo-tsla',
    type: 'buy',
    datetime: '2026-03-12T11:10:00Z',
    investedAmount: '2200',
    investedCurrency: 'EUR',
    quantity: '8.0672333333',
    executionPrice: '272.71',
    quoteCurrency: 'EUR',
    fee: null,
    feeCurrency: null,
    sourceType: 'historical_estimate',
    confidence: 'medium',
    estimationNotes: 'Precio de ejecucion ficticio derivado del historico demo.',
    isDemo: true,
  },
  {
    id: 'demo-tx-cash-1',
    accountId: 'demo-acc-cash',
    assetId: 'demo-cash-eur',
    type: 'buy',
    datetime: '2026-01-02T09:00:00Z',
    investedAmount: '991.11',
    investedCurrency: 'EUR',
    quantity: '991.11',
    executionPrice: '1',
    quoteCurrency: 'EUR',
    fee: null,
    feeCurrency: null,
    sourceType: 'exact',
    confidence: 'exact',
    isDemo: true,
  },
]

const DEMO_FETCHED_AT = '2026-07-20T10:00:00Z'

export const DEMO_QUOTES: Quote[] = [
  {
    assetId: 'demo-btc',
    price: '66500',
    currency: 'USD',
    timestamp: DEMO_FETCHED_AT,
    provider: 'demo',
    quality: 'demo',
    fetchedAt: DEMO_FETCHED_AT,
  },
  {
    assetId: 'demo-msci-world-etf',
    price: '98.50',
    currency: 'EUR',
    timestamp: DEMO_FETCHED_AT,
    provider: 'demo',
    quality: 'demo',
    fetchedAt: DEMO_FETCHED_AT,
  },
  {
    assetId: 'demo-spx-etf',
    price: '575.85',
    currency: 'EUR',
    timestamp: DEMO_FETCHED_AT,
    provider: 'demo',
    quality: 'demo',
    fetchedAt: DEMO_FETCHED_AT,
  },
  {
    assetId: 'demo-aapl',
    price: '220',
    currency: 'USD',
    timestamp: DEMO_FETCHED_AT,
    provider: 'demo',
    quality: 'demo',
    fetchedAt: DEMO_FETCHED_AT,
  },
  {
    assetId: 'demo-tsla',
    price: '330',
    currency: 'USD',
    timestamp: DEMO_FETCHED_AT,
    provider: 'demo',
    quality: 'demo',
    fetchedAt: DEMO_FETCHED_AT,
  },
  {
    assetId: 'demo-cash-eur',
    price: '1',
    currency: 'EUR',
    timestamp: DEMO_FETCHED_AT,
    provider: 'demo',
    quality: 'demo',
    fetchedAt: DEMO_FETCHED_AT,
  },
]

export const DEMO_FX_EURUSD = {
  base: 'EUR' as const,
  quote: 'USD' as const,
  rate: '1.10',
  date: '2026-07-20',
  provider: 'demo',
  quality: 'demo' as const,
  fetchedAt: DEMO_FETCHED_AT,
}
