/**
 * Datos de demostracion FICTICIOS. Simbolos reales, cantidades y precios
 * inventados. Todo lleva isDemo: true y la UI lo etiqueta como "Datos demo".
 * Permiten usar la aplicacion completa sin claves de ningun proveedor.
 */
import type { Asset, BrokerAccount, Quote, Transaction } from '../lib/domain'

export const DEMO_PORTFOLIO_TARGET_EUR = '23049.26'

export const DEMO_ACCOUNTS: BrokerAccount[] = [
  {
    id: 'demo-acc-broker',
    brokerName: 'Broker Demo',
    accountLabel: 'Cartera indexada (demo)',
    defaultCurrency: 'EUR',
    country: 'ES',
  },
  {
    id: 'demo-acc-exchange',
    brokerName: 'Exchange Demo',
    accountLabel: 'Cripto (demo)',
    defaultCurrency: 'EUR',
  },
  {
    id: 'demo-acc-cash',
    brokerName: 'Banco Demo',
    accountLabel: 'Liquidez (demo)',
    defaultCurrency: 'EUR',
    country: 'ES',
  },
]

export const DEMO_ASSETS: Asset[] = [
  {
    id: 'demo-btc',
    symbol: 'BTC',
    name: 'Bitcoin',
    assetType: 'crypto',
    quoteCurrency: 'USD',
    providerIds: { coingecko: 'bitcoin', twelvedata: 'BTC/USD' },
    sector: 'Criptoactivo',
    country: 'Global',
    isDemo: true,
  },
  {
    id: 'demo-spx-etf',
    symbol: 'SXR8',
    name: 'iShares Core S&P 500 UCITS ETF (Acc)',
    assetType: 'etf',
    quoteCurrency: 'EUR',
    isin: 'IE00B5BMR087',
    exchange: 'XETRA',
    country: 'US',
    sector: 'Renta variable EEUU',
    providerIds: { twelvedata: 'SXR8' },
    holdings: [
      { symbol: 'AAPL', name: 'Apple', weight: '0.072' },
      { symbol: 'MSFT', name: 'Microsoft', weight: '0.066' },
      { symbol: 'NVDA', name: 'NVIDIA', weight: '0.058' },
    ],
    isDemo: true,
  },
  {
    id: 'demo-world-etf',
    symbol: 'VWCE',
    name: 'Vanguard FTSE All-World UCITS ETF (Acc)',
    assetType: 'etf',
    quoteCurrency: 'EUR',
    isin: 'IE00BK5BQT80',
    exchange: 'XETRA',
    country: 'Global',
    sector: 'Renta variable global',
    providerIds: { twelvedata: 'VWCE' },
    holdings: [
      { symbol: 'AAPL', name: 'Apple', weight: '0.044' },
      { symbol: 'MSFT', name: 'Microsoft', weight: '0.039' },
      { symbol: 'NVDA', name: 'NVIDIA', weight: '0.034' },
    ],
    isDemo: true,
  },
  {
    id: 'demo-gold',
    symbol: 'ORO',
    name: 'Oro fisico equivalente (demo)',
    assetType: 'commodity',
    quoteCurrency: 'EUR',
    manualPrice: { price: '76.40', currency: 'EUR', updatedAt: '2026-07-20T10:00:00Z' },
    sector: 'Materias primas',
    country: 'Global',
    isDemo: true,
  },
  {
    id: 'demo-cash-eur',
    symbol: 'EUR',
    name: 'Efectivo EUR',
    assetType: 'cash',
    quoteCurrency: 'EUR',
    sector: 'Liquidez',
    country: 'ES',
    isDemo: true,
  },
]

export const DEMO_TRANSACTIONS: Transaction[] = [
  {
    id: 'demo-tx-btc-1',
    accountId: 'demo-acc-exchange',
    assetId: 'demo-btc',
    type: 'buy',
    datetime: '2025-08-12T09:30:00Z',
    investedAmount: '1200',
    investedCurrency: 'EUR',
    quantity: '0.034',
    executionPrice: '38824',
    quoteCurrency: 'USD',
    fee: null,
    feeCurrency: null,
    sourceType: 'historical_estimate',
    confidence: 'medium',
    estimationNotes: 'Precio de ejecucion ficticio derivado del historico demo.',
    isDemo: true,
  },
  {
    id: 'demo-tx-btc-2',
    accountId: 'demo-acc-exchange',
    assetId: 'demo-btc',
    type: 'buy',
    datetime: '2026-02-06T10:15:00Z',
    investedAmount: '1450',
    investedCurrency: 'EUR',
    quantity: '0.027',
    executionPrice: '59074',
    quoteCurrency: 'USD',
    fee: null,
    feeCurrency: null,
    sourceType: 'historical_estimate',
    confidence: 'medium',
    estimationNotes: 'Precio de ejecucion ficticio derivado del historico demo.',
    isDemo: true,
  },
  {
    id: 'demo-tx-btc-3',
    accountId: 'demo-acc-exchange',
    assetId: 'demo-btc',
    type: 'buy',
    datetime: '2026-05-07T08:40:00Z',
    investedAmount: '1225',
    investedCurrency: 'EUR',
    quantity: '0.025',
    executionPrice: '53900',
    quoteCurrency: 'USD',
    fee: null,
    feeCurrency: null,
    sourceType: 'historical_estimate',
    confidence: 'medium',
    estimationNotes: 'Precio de ejecucion ficticio derivado del historico demo.',
    isDemo: true,
  },
  {
    id: 'demo-tx-spx-1',
    accountId: 'demo-acc-broker',
    assetId: 'demo-spx-etf',
    type: 'buy',
    datetime: '2025-09-04T14:00:00Z',
    investedAmount: '2600',
    investedCurrency: 'EUR',
    quantity: '5',
    executionPrice: '520',
    quoteCurrency: 'EUR',
    fee: null,
    feeCurrency: null,
    sourceType: 'exact',
    confidence: 'exact',
    isDemo: true,
  },
  {
    id: 'demo-tx-spx-2',
    accountId: 'demo-acc-broker',
    assetId: 'demo-spx-etf',
    type: 'buy',
    datetime: '2026-01-16T14:05:00Z',
    investedAmount: '2250',
    investedCurrency: 'EUR',
    quantity: '4',
    executionPrice: '562.50',
    quoteCurrency: 'EUR',
    fee: null,
    feeCurrency: null,
    sourceType: 'exact',
    confidence: 'exact',
    isDemo: true,
  },
  {
    id: 'demo-tx-spx-3',
    accountId: 'demo-acc-broker',
    assetId: 'demo-spx-etf',
    type: 'buy',
    datetime: '2026-04-23T13:55:00Z',
    investedAmount: '1650',
    investedCurrency: 'EUR',
    quantity: '3',
    executionPrice: '550',
    quoteCurrency: 'EUR',
    fee: null,
    feeCurrency: null,
    sourceType: 'exact',
    confidence: 'exact',
    isDemo: true,
  },
  {
    id: 'demo-tx-world-1',
    accountId: 'demo-acc-broker',
    assetId: 'demo-world-etf',
    type: 'buy',
    datetime: '2025-10-10T14:00:00Z',
    investedAmount: '1650',
    investedCurrency: 'EUR',
    quantity: '15',
    executionPrice: '110',
    quoteCurrency: 'EUR',
    fee: null,
    feeCurrency: null,
    sourceType: 'exact',
    confidence: 'exact',
    isDemo: true,
  },
  {
    id: 'demo-tx-world-2',
    accountId: 'demo-acc-broker',
    assetId: 'demo-world-etf',
    type: 'buy',
    datetime: '2026-02-18T14:00:00Z',
    investedAmount: '1130',
    investedCurrency: 'EUR',
    quantity: '10',
    executionPrice: '113',
    quoteCurrency: 'EUR',
    fee: null,
    feeCurrency: null,
    sourceType: 'exact',
    confidence: 'exact',
    isDemo: true,
  },
  {
    id: 'demo-tx-world-3',
    accountId: 'demo-acc-broker',
    assetId: 'demo-world-etf',
    type: 'buy',
    datetime: '2026-06-02T14:00:00Z',
    investedAmount: '1155',
    investedCurrency: 'EUR',
    quantity: '10',
    executionPrice: '115.50',
    quoteCurrency: 'EUR',
    fee: null,
    feeCurrency: null,
    sourceType: 'exact',
    confidence: 'exact',
    isDemo: true,
  },
  {
    id: 'demo-tx-gold-1',
    accountId: 'demo-acc-broker',
    assetId: 'demo-gold',
    type: 'buy',
    datetime: '2025-11-20T11:00:00Z',
    investedAmount: '1320',
    investedCurrency: 'EUR',
    quantity: '20',
    executionPrice: '66',
    quoteCurrency: 'EUR',
    fee: null,
    feeCurrency: null,
    sourceType: 'return_estimate',
    confidence: 'medium',
    estimationNotes: 'Cantidad ficticia para una posicion demo en oro.',
    isDemo: true,
  },
  {
    id: 'demo-tx-gold-2',
    accountId: 'demo-acc-broker',
    assetId: 'demo-gold',
    type: 'buy',
    datetime: '2026-03-12T11:10:00Z',
    investedAmount: '980',
    investedCurrency: 'EUR',
    quantity: '14.25',
    executionPrice: '68.77',
    quoteCurrency: 'EUR',
    fee: null,
    feeCurrency: null,
    sourceType: 'return_estimate',
    confidence: 'medium',
    estimationNotes: 'Cantidad ficticia para una posicion demo en oro.',
    isDemo: true,
  },
  {
    id: 'demo-tx-gold-3',
    accountId: 'demo-acc-broker',
    assetId: 'demo-gold',
    type: 'buy',
    datetime: '2026-05-29T11:05:00Z',
    investedAmount: '720',
    investedCurrency: 'EUR',
    quantity: '10',
    executionPrice: '72',
    quoteCurrency: 'EUR',
    fee: null,
    feeCurrency: null,
    sourceType: 'return_estimate',
    confidence: 'medium',
    estimationNotes: 'Cantidad ficticia para una posicion demo en oro.',
    isDemo: true,
  },
  {
    id: 'demo-tx-cash-1',
    accountId: 'demo-acc-cash',
    assetId: 'demo-cash-eur',
    type: 'buy',
    datetime: '2026-01-02T09:00:00Z',
    investedAmount: '3308.87',
    investedCurrency: 'EUR',
    quantity: '3308.87',
    executionPrice: '1',
    quoteCurrency: 'EUR',
    fee: null,
    feeCurrency: null,
    sourceType: 'exact',
    confidence: 'exact',
    isDemo: true,
  },
]

const DEMO_FETCHED_AT = '2026-07-20T10:00:00Z'

export const DEMO_QUOTES: Quote[] = [
  {
    assetId: 'demo-btc',
    price: '66500',
    currency: 'USD',
    timestamp: DEMO_FETCHED_AT,
    provider: 'demo',
    quality: 'demo',
    fetchedAt: DEMO_FETCHED_AT,
  },
  {
    assetId: 'demo-spx-etf',
    price: '575.85',
    currency: 'EUR',
    timestamp: DEMO_FETCHED_AT,
    provider: 'demo',
    quality: 'demo',
    fetchedAt: DEMO_FETCHED_AT,
  },
  {
    assetId: 'demo-world-etf',
    price: '121.44',
    currency: 'EUR',
    timestamp: DEMO_FETCHED_AT,
    provider: 'demo',
    quality: 'demo',
    fetchedAt: DEMO_FETCHED_AT,
  },
  {
    assetId: 'demo-gold',
    price: '76.40',
    currency: 'EUR',
    timestamp: DEMO_FETCHED_AT,
    provider: 'demo',
    quality: 'demo',
    fetchedAt: DEMO_FETCHED_AT,
  },
  {
    assetId: 'demo-cash-eur',
    price: '1',
    currency: 'EUR',
    timestamp: DEMO_FETCHED_AT,
    provider: 'demo',
    quality: 'demo',
    fetchedAt: DEMO_FETCHED_AT,
  },
]

export const DEMO_FX_EURUSD = {
  base: 'EUR' as const,
  quote: 'USD' as const,
  rate: '1.10',
  date: '2026-07-20',
  provider: 'demo',
  quality: 'demo' as const,
  fetchedAt: DEMO_FETCHED_AT,
}
